flora/urls.py
from django.conf.urls import url

from . import views

app_name = 'flora'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<plant_id>[0-9]+)/$', views.plante, name='plante'),
    url(r'^planteliste/', views.planteliste, name='planteliste'),
    url(r'^familieliste/', views.familieliste, name='familieliste'),
    url(r'^search/', views.search, name='search'),
    url(r'^familie/', views.familie, name='familie'),
    url(r'^famile_latin/', views.familieliste_latin, name='familieliste_latin'),
    url(r'^slide/', views.slide, name='slide'),
    url(r'^kontakt/', views.kontakt, name='kontakt')
]

floraRuden/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^flora/', include('flora.urls')),
    url(r'^admin/', admin.site.urls),
]

flora/models.py
from __future__ import unicode_literals

from django.db import models
from sorl.thumbnail import ImageField

class Plant(models.Model):
    norwegian_name = models.CharField(max_length=100)
    latin_name = models.CharField(max_length=100, blank=True)
    english_name = models.CharField(max_length=100, blank=True)
    norwegian_family = models.CharField(max_length=100)
    latin_family = models.CharField(max_length=100)
    english_family = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    def __unicode__(self):
        return self.norwegian_name

class Picture(models.Model):
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    date_taken = models.DateField()
    date_added = models.DateField(auto_now_add=True)
    picture = models.ImageField()
    def __unicode__(self):
        return self.plant.norwegian_name + str(self.pk)

flora/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Plant
import math

def index(request):
    return render(request, 'flora/index.html')

def planteliste(request):
    pl = Plant.objects.all().order_by('norwegian_name')
    n = math.ceil(pl.count()/3.0)
    splitListe = [pl[i:i+int(n)] for i in xrange(0, len(pl), int(n))]
    context = {
        'splitListe0': splitListe[0],
        'splitListe1': splitListe[1],
        'splitListe2': splitListe[2],
    }
    return render(request, 'flora/planteliste.html', context)

def familieliste(request):
    familieliste = []
    planteliste = Plant.objects.all()
    for plant in planteliste:
        familieliste.append(plant.norwegian_family)
    familieliste = set(familieliste)
    familieliste = sorted(familieliste)
    context = {
        'familieliste': familieliste
    }
    return render(request, 'flora/familieliste.html', context)

def familieliste_latin(request):
    familieliste = []
    planteliste = Plant.objects.all()
    for plant in planteliste:
        familieliste.append(plant.latin_family)
    familieliste = set(familieliste)
    familieliste = sorted(familieliste)
    context = {
        'familieliste': familieliste
    }
    return render(request, 'flora/familieliste.html', context)

def plante(request, plant_id):
    plant = get_object_or_404(Plant, pk=plant_id)
    pictures = plant.picture_set.all()
    context = {
        'plant': plant,
        'pictures': pictures,
    }
    return render(request, 'flora/detail.html', context)

def search(request):
    searchText = request.POST.get("search")
    result = Plant.objects.filter(norwegian_name__iexact=searchText)
    result = result | Plant.objects.filter(norwegian_family__iexact=searchText)
    result = result | Plant.objects.filter(latin_family__iexact=searchText)
    context = {
        'result': result,
        'searchText': searchText,
    }
    return render(request, 'flora/search.html', context)

def familie(request):
    path = request.path
    pathEnd = path.split("/")
    pathLength = len(pathEnd)
    searchText = pathEnd[pathLength-1]
    result = Plant.objects.filter(norwegian_family__iexact=searchText)
    result = result | Plant.objects.filter(latin_family__iexact=searchText)
    context = {
        'result': result,
        'searchText': searchText,
    }
    return render(request, 'flora/search.html', context)

def kontakt(request):
    return render(request, 'flora/kontakt.html')

def slide(request):
    path = request.path
    pathEnd = path.split("/")
    pathLength = len(pathEnd)
    searchText = pathEnd[pathLength-2]
    plant = Plant.objects.get(pk=searchText)
    pictures = plant.picture_set.all()
    firstPic = pictures.first()
    context = {
        'plant': plant,
        'pictures': pictures,
        'firstPic': firstPic,
    }
    return render(request, 'flora/slide.html', context)

flora/templates/flora/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="cs" />
    <meta name="author" lang="cs" content="" />
    <meta name="copyright" lang="cs" content="" />
    <meta name="description" content="..." />
    <meta name="keywords" content="..." />
    <meta name="robots" content="all,follow" />
    <link href="{% static 'flora/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection" />
    {% block head %}
    {% endblock %}

    <title>Flora Ruden</title>
  </head>
  <body>
    <div id="layout">
      <div id="header">

        <h1 id="logo"><a href="{% url 'flora:index' %}" title="Flora Ruden">Flora Ruden</a></h1>
        <hr class="noscreen" />

      </div>

      <hr class="noscreen" />

      <div id="nav" class="box">
        <ul>
        <li title="hjem"><a href="{% url 'flora:index' %}">Hjem</a></li>
        <li title="pl"><a href="{% url 'flora:planteliste' %}">Planteliste</a></li>
        <li title="fln"><a href="{% url 'flora:familieliste' %}">Familieliste norsk</a></li>
        <li title="fll"><a href="{% url 'flora:familieliste_latin' %}">Familieliste latin</a></li>
        <li title="ko"><a href="{% url 'flora:kontakt' %}">Kontakt oss</a></li>
				</ul>
        <hr class="noscreen" />
      </div>

      <div id="container" class="box">
          <div id="intro">
            <div id="intro-in">
            <h2>Wælkjømmen te Flora Ruden</h2>
            <p class="intro">
              Denne siden er under utvikling. Siden er i et så tidlig stadie at
              det faktisk er umulig å ha en side i et tidligere utviklingstadie.
               Så det så!
            </p>
            </div>
          </div>
          <div id="obsah" class="content box">
          <div class="in">
<!--            <div class="shadow">

            <img src="{% static 'flora/images/Anemone-Color-Meaning.jpg' %}" alt="image.jpg" title="image.jpg" class="thumb" />
            </div>
-->
            {% block content %}
            {% endblock %}
            <div class="clear"></div>
          </div>
        </div>
      </div>

      <div id="footer" class="shadow">
        <div class="f-left">
          Til informasjon: Dette kommer til å bli verdens beste nettside.
        </div>
      </div>
    </div>
    {% block script %}
    <script src="{% static 'flora/jquery-3.1.1.js' %}"></script>
    <script src="{% static 'flora/base.js' %}"></script>
    {% endblock %}
  </body>
</html>

flora/templates/flora/detail.html
{% extends 'flora/base.html' %}
{% load thumbnail %}

{% block content %}
<h1>{{ plant }}:</h1>
<p>
  Norsk familie: <a href="{% url 'flora:familie' %}{{ plant.norwegian_family }}">
    {{ plant.norwegian_family }}</a><br>
  Latinsk familie: {{ plant.latin_family }}
</p>
<h3>Beskrivelse</h3>
<p> {{ plant.description|safe }} </p>
{% if pictures %}
  <h3>Bilder:</h3>
  {% for picture in pictures %}
    <a href="{% url 'flora:slide' %}{{ plant.pk }}/{{ forloop.counter }}">
      {% thumbnail picture.picture "219" crop="center" as im %}
        <img src="{{ im.url }}" alt="{{ forloop.counter }}" width="{{ im.width }}" height="{{ im.height }}">
      {% empty %}
        <p>No image: {{ picture.picture.url }}</p>
      {% endthumbnail %}
    </a>
  {% endfor %}
{% else %}
  <p>Fant ingen bilder for denne planten</p>
{% endif %}
{% endblock %}

flora/templates/flora/familieliste.html
{% extends 'flora/base.html' %}

{% block content %}
<div>
    <p>
      <form action="{% url 'flora:search' %}" method="post">
        {% csrf_token %}
        Søk etter plante eller familie:<br>
        <input type="text" name="search" maxlength="50">
        <input type="submit" value=" Søk ">
      </form>
    </p>
</div>
<div>
  <h3>Familieliste</h3>
  <div class="col1">
    <ul>
      {% if familieliste %}
        {% for plant in familieliste %}
          <li>
            <a href="{% url 'flora:familie' %}{{ plant }}">{{ plant }}</a>
          </li>
        {% endfor %}
      {% else %}
        <p>Fant ingen planter.</p>
      {% endif %}
    </ul>
  </div>
</div>
{% endblock %}

flora/templates/flora/index.html
{% extends 'flora/base.html' %}

{% block content %}
<h2>Søk:</h2>
<p>
  <form action="{% url 'flora:search' %}" method="post">
    {% csrf_token %}
    Her kan du søke etter våre vakre planter:<br>
    <input type="text" name="search" maxlength="50">
    <input type="submit" value=" Søk ">
  </form>
</p>
{% endblock %}

flora/templates/flora/kontakt.html
{% extends 'flora/base.html' %}

{% block content %}
<h1>Kontakt</h1>
<p>
  Her skal det komme litt info om oss og opplegg for å sende inn forslag til
  forbedringer
</p>
{% endblock %}

flora/templates/flora/planteliste.html
{% extends 'flora/base.html' %}

{% block content %}
<div>
    <p>
      <form action="{% url 'flora:search' %}" method="post">
        {% csrf_token %}
        Søk etter plante eller familie:<br>
        <input type="text" name="search" maxlength="50">
        <input type="submit" value=" Søk ">
      </form>
    </p>
</div>
<div>
  <h3>Planteliste</h3>
  <div class="col1">
  <ul>
        {% if splitListe0 %}
            {% for plant in splitListe0 %}
                <li><a href="{% url 'flora:plante' plant.id %}">{{ plant.norwegian_name }}</a></li>
            {% endfor %}
        {% else %}
            <p>En feil har oppstått.</p>
        {% endif %}
  </ul>
  </div>
  <div class="col1">
  <ul>
        {% if splitListe1 %}
            {% for plant in splitListe1 %}
                <li><a href="{% url 'flora:plante' plant.id %}">{{ plant.norwegian_name }}</a></li>
            {% endfor %}
        {% else %}
            <p>En feil har oppstått.</p>
        {% endif %}
  </ul>
  </div>
  <div class="col1">
  <ul>
        {% if splitListe2 %}
            {% for plant in splitListe2 %}
                <li><a href="{% url 'flora:plante' plant.id %}">{{ plant.norwegian_name }}</a></li>
            {% endfor %}
        {% else %}
            <p>En feil har oppstått.</p>
        {% endif %}
  </ul>
  </div>
</div>
{% endblock %}

flora/templates/flora/search.html
{% extends 'flora/base.html' %}

{% block content %}
<h3>Søkeresultat</h3>
<p>
  {% if result %}
  Du søkte etter: {{ searchText }}.<br>
  Resultat:<br><br>
    {% for plant in result %}
      Norsk navn: <a href="{% url 'flora:plante' plant.id %}">{{ plant.norwegian_name }}</a><br>
      Norsk familie: {{ plant.norwegian_family}}<br>
      Latinsk familie: {{ plant.latin_family}}<br><br>
    {% endfor %}
  {% else %}
    Du søkte etter: {{ searchText }}.<br>
    Fant ikke planten du søkte etter<br>
  {% endif %}
</p>
{% endblock %}

flora/templates/flora/slide.html
{% extends 'flora/base.html' %}
{% load static %}

{% block head %}
  <link href="{% static 'flora/slide.css' %}" type="text/css" rel="stylesheet"/>
{% endblock %}

{% block content %}
{% if pictures %}
  <div id="slider">
    <ul class="slides">
      {% for picture in pictures %}
        <li class="slide">
          <img src="{{ picture.picture.url }}" width="890"/>
        </li>
      {% endfor %}
        <li class="slide">
          <img src="{{ firstPic.picture.url }}" width="890"/>
        </li>
      </ul>
    <button class="navButton prev" name="prev"><</button>
    <button class="navButton next" name="next">></button>
  </div>
{% else %}
  <p>Fant ingen bilder for denne planten</p>
{% endif %}
{% endblock %}

{% block script %}
<script src="{% static 'flora/jquery-3.1.1.js' %}"></script>
<script src="{% static 'flora/slide.js' %}"></script>
{% endblock %}